version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://idir:etnascape@db:5432/clo
    command: gunicorn API_CLO.wsgi:application --bind 0.0.0.0:8000
    networks:
      - api_network
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: clo
      POSTGRES_USER: idir
      POSTGRES_PASSWORD: etnascape
    ports:
      - "5432:5432"
    networks:
      - api_network
networks:
  api_network:
